name: Node.js CI

on:
  push:
    branches: [ main-4.x ]
  pull_request:
    branches: [ main-4.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.0.x, 12.13.x, 12.x, 14.0.x, 14.13.x, 14.17.x, 14.x, 16.x, 18.x, 19.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test:ci
      env:
        CI: true
